### PR TITLE
add Eclipse & NetBeans settings files to .gitignore

### PR DESCRIPTION
**Pull request by mtbc**
If acceptable then I'll open for the other repos.

### CODE REVIEW

**Comment by joshmoore** [comment]
Certainly works for me. If you are opening N Prs though I wonder if there's anything else we want adding at this time?

**Comment by mtbc** [comment]
Good question: have now asked in stand-up.

**Comment by rgozim** [comment]
could we also add `.vscode/*`?

**Comment by dominikl** [comment]
Maybe also `.idea` (IntelliJ)?

**Comment by joshmoore** [comment]
No objections to adding or getting this in. An alternative, though, might be to add this information to the `.gittemplates` directory that we all share.

**Comment by mtbc** [comment]
We do? (I probably missed something.)

**Comment by joshmoore** [comment]
Do now: https://github.com/ome/gittemplates

**Comment by mtbc** [comment]
Is it clear how such information would be added? There would still be scope for making it somewhat repository-specific?

**Comment by joshmoore** [comment]
> Is it clear how such information would be added?

i.e. by updating https://github.com/ome/gittemplates/blob/master/info/exclude ?

> There would still be scope for making it somewhat repository-specific?

No, not in that case. But this would be just a template that you can edit as needed.

> It would be standard to ignore the .gitignore file itself?

Typically, no. It's ok to have gitignore files in a repo for things that are project specific, but if we are creating things due to a common workflow, then perhaps the template is better. I don't have proof of that yet, and third-parties would still be left needing to configure things themselves.

**Comment by mtbc** [comment]
Aha, I was looking for something with "ignore" in the name. :smiley:

**Comment by mtbc** [comment]
Closing for now to minimize clutter until we decide about https://github.com/ome/omero-model/pull/12#issuecomment-476174751.

**Comment by mtbc** [comment]
I think probably best not to attempt this given the range of IDEs users might employ and the maintenance burden for us. Having RTFM plenty I now find that if I put some excludes into `~/.config/git/ignore` then they apply broadly without cluttering our code repos.

**Comment by joshmoore** [comment]
> ~/.config/git/ignore

Ah, thanks!

**Pull request closed without merging**
