### PR TITLE
Add index on originalfile (path || name) Fix #71

### LINKED ISSUE #71: 5.6.1 image file access is very slow on IDR
OMERO.server 5.6.1 introduced a validation check to prevent malicious image files gaining access to other data: https://ome-www-dev.openmicroscopy.org/security/advisories/2019-SV1/
This check takes too long on the IDR- the readonly servers have a PostgreSQL statement timeout of 1 minute and the query is timing out.

Testing on the read-write server which has no timeout also takes a long time, I cancelled the request after a few minutes.

This takes less than a second to run on 5.6.0, output should be `(2048, 2169)`:
```python
#!/opt/omero/server/venv3/bin/python
from omero.gateway import BlitzGateway
conn = BlitzGateway(host='localhost', username='public', passwd='public', secure=True)
assert conn.connect()
im = conn.getObject('Image', 4007802)
px = im.getPrimaryPixels()
plane = px.getPlane(0, 0, 0)
print(plane.shape)
conn.close()
```
It times out on 5.6.1

### PR DESCRIPTION
**Pull request by joshmoore**
2019-SV1 led to a slow down in file lookups. This adds
an index which should correct the issue.

--exclude

### CODE REVIEW

**Comment by sbesson** [comment]
From https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-server/807/

```
DB version (OMERO5.4__1) does not match the configured value (OMERO5.4__0). Please apply a db upgrade.
```

I assume `omero.db.patch` should be incremented?

**Comment by joshmoore** [comment]
Hmmm.... I was assuming since I *didn't* bump the patch, it wouldn't become active yet.

**Comment by sbesson** [comment]
I suspect it's a feature of `omego` which seems to automatically detect all available SQL upgrade scripts and apply them independently of the value of `omero.db.patch`

**Comment by joshmoore** [comment]
@sbesson : do you have a feeling for the need for this?

**Comment by sbesson** [comment]
Using an empty DB, without the index

```
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero fs importtime Fileset:5
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: demo
   upload time of 22721.45s for 112643 files (0.202s/file)
    setId time of 192.69s
 metadata time of 8498.81s
   pixels time of 27927.20s for 112640 planes (0.248s/plane)
    rdefs time of 4743.31s for 3520 rendering settings (1.348s/rdef)
thumbnail time of 4798.51s for 3520 thumbnails (1.363s/thumbnail)
```

with the index

```
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero fs importtime Fileset:6
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: demo
   upload time of 15607.63s for 112643 files (0.139s/file)
    setId time of 179.97s
 metadata time of 8375.22s
   pixels time of 22306.67s for 112640 planes (0.198s/plane)
    rdefs time of 4763.36s for 3520 rendering settings (1.353s/rdef)
thumbnail time of 4712.14s for 3520 thumbnails (1.339s/thumbnail)
```

**Comment by sbesson** [comment]
Finally managed to perform the same testing on a non-empty DB ( state of IDR as per `prod100`)

Without the index:

```
   upload time of 58274.82s for 112643 files (0.517s/file)
    setId time of 171.32s
 metadata time of 7739.96s
   pixels time of 20519.34s for 112640 planes (0.182s/plane)
    rdefs time of 4908.79s for 3520 rendering settings (1.395s/rdef)
thumbnail time of 4957.34s for 3520 thumbnails (1.408s/thumbnail)
```

With the index:

```
   upload time of 54545.20s for 112643 files (0.484s/file)
    setId time of 178.71s
 metadata time of 7579.33s
   pixels time of 21058.39s for 112640 planes (0.187s/plane)
    rdefs time of 4734.95s for 3520 rendering settings (1.345s/rdef)
thumbnail time of 4709.67s for 3520 thumbnails (1.338s/thumbnail)
```

**Comment by joshmoore** [comment]
I.e. little of value here, eh?

**Comment by sbesson** [comment]
> I.e. little of value here, eh?

I was about to reach this conclusion and comment publicly to that effect but I then realize all of the above has been tested on OMERO 5.6.0 which does not include the 2019-SV1 fix above.

One issue here is that this index was proposed to address two separate issues:

- https://github.com/ome/omero-model/issues/71  which is suggested to be related to the 2019-SV1 fix
- https://github.com/ome/omero-blitz/issues/73 which is independent of the 2019-SV1 fix

I think the metrics above demonstrated that the index is not sufficient to significantly reduce the upload times for large DBs.

I propose to recreate a deployment with OMERO 5.6.3 and measure the import times with/without index (and maybe the access times) to see if there is an extra overhead related to the security fix that would still be addressed by the index.

**Comment by sbesson** [comment]
Also measured the slow image file access

```python
#!/opt/omero/server/venv3/bin/python
from omero.gateway import BlitzGateway
import time
start = time.time()
conn = BlitzGateway(host='localhost', username='public', passwd='public', secure=True)
assert conn.connect()
start = time.time()
im = conn.getObject('Image', 4007802)
px = im.getPrimaryPixels()
plane = px.getPlane(0, 0, 0)
print(plane.shape)
print(time.time() - start)
conn.close()
```

From `prod100` (read-only server)

```
[sbesson@prod100-omeroreadonly-1 ~]$  /opt/omero/server/venv3/bin/python test.py 
(2048, 2169)
0.6803202629089355
[sbesson@prod100-omeroreadonly-1 ~]$  /opt/omero/server/venv3/bin/python test.py 
(2048, 2169)
0.6405618190765381
[sbesson@prod100-omeroreadonly-1 ~]$  /opt/omero/server/venv3/bin/python test.py 
(2048, 2169)
0.6546294689178467
```

From the pilot server with OMERO.server 5.6.3, after waiting for the cache file regeneration:

```
[sbesson@pilot-idrgerman-omeroreadwrite ~]$ /opt/omero/server/venv3/bin/python test.py 
(2048, 2169)
0.5594687461853027
[sbesson@pilot-idrgerman-omeroreadwrite ~]$ /opt/omero/server/venv3/bin/python test.py 
(2048, 2169)
0.5589122772216797
[sbesson@pilot-idrgerman-omeroreadwrite ~]$ /opt/omero/server/venv3/bin/python test.py 
(2048, 2169)
0.6080117225646973
```

Effectively, I cannot reproduce https://github.com/ome/omero-model/issues/71  this index does not significantly address the https://github.com/ome/omero-blitz/issues/73. Proposing to close #71 and this PR.

**Comment by joshmoore** [comment]
Done.

**Pull request closed without merging**
