### PR TITLE
Properties file

### PR DESCRIPTION
**Pull request by jburel**
Add Properties file

### CODE REVIEW

**Comment by joshmoore** [comment]
Why 2 files?

**Comment by jburel** [comment]
hum it should only be one, something went wrong with the IDE
I will fix that

**Comment by jburel** [comment]
sorted

**Comment by jburel** [comment]
Moved ``omero.db.*`` properties here so we can set the ``omero.db.profile`` during the build and be sure it matches the one set in ``build.gradle``

**Comment by jburel** [comment]
Merging and tagging

**Pull request merged**
