### PR TITLE
Changes for m4 

### PR DESCRIPTION
**Pull request by rgozim**

### CODE REVIEW

**Comment by jburel** [comment]
@rgozim you will have to roll back the change to SNAPSHOT since it has already been done in
another PR

**Comment by jburel** [comment]
``omero-blitz-5.5.0-SNAPSHOT-python.zip`` is no longer created
This prevents ``openmicroscpy`` build to work

**Comment by jburel** [comment]
I might be missing something but there is no such thing on artifactory 
```[id: 'org.openmicroscopy.project', version: '5.5.0-SNAPSHOT']```

**Comment by joshmoore** [comment]
https://github.com/ome/omero-blitz-plugin/pull/6 is still not released but that doesn't block this PR. Might be worth taking a quick glance this morning, and then we can jump to this next phase.

**Comment by joshmoore** [comment]
Moving forward with the release of 5.5.0-m4.

**Pull request merged**
