### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rgozim**

### CODE REVIEW

**Comment by joshmoore** [comment]
Only two issues to raise are the change to `unidata-all` which may need to be revisited and the addition of the mapping files which have now lost their history. I'll almost certainly rewrite these commits to tie those files back together.

Otherwise, last call for issues so I can merge in preparation for rc3.

**Comment by jburel** [comment]
W should stick to ``unidata-relases`` (missing ``/`` at the end)

**Comment by rgozim** [comment]
The unidata docs for netcdf show the repository `unidata-all`. I'm not sure why they state on the docs that `unidata-all` is their _release_ repo, when on another doc page they mention `unidata-release`.

Link to docs:
https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/BuildDependencies.html

**Comment by joshmoore** [comment]
Merging for 5.5-m3. We can adjust `unidata` in a follow-up.

**Pull request merged**
