### PR TITLE
bump org.openmicroscopy.project 5.6.0

### PR DESCRIPTION
**Pull request by jburel**
Bump version to fix javadoc generation issue

### CODE REVIEW

**Comment by sbesson** [comment]
Is this still a candidate for the next omero-model release? What is the best way to test it?

**Comment by jburel** [comment]
This is mainly when we upgrade to the next jenkins. I can be omitted for the next release

**Comment by jburel** [comment]
This has been included in the build for a long time. This was required to have Jenkins CI green

**Review by sbesson — APPROVED** [review]
My understanding is that this is related to https://github.com/ome/omero-artifact-plugin/pull/21 which is a requirement for building the Javadoc on JDK 11+

**Comment by sbesson** [comment]
I assume this was superseded by https://github.com/ome/omero-model/pull/107 and can be closed?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-build-push#247](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/247/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/247/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - build.gradle

--conflicts

**Pull request closed without merging**
