### PR TITLE
Provide SQL means of fetching users' pretty name and e-mail.

### PR DESCRIPTION
**Pull request by mtbc**
Allow bypassing Hibernate security checks in obtaining users' name and e-mail.

### CODE REVIEW

**Comment by joshmoore** [comment]
In addition to https://github.com/ome/omero-blitz/pull/85#issuecomment-610055435 we likely need to discuss the semver-ness of this repository with respect to `SqlAction` where we've tended to be fairly loose.

**Comment by mtbc** [comment]
Indeed, good point: my adding SqlAction methods breaks anybody implementing the public interface, perhaps including Glencoe, so probably worth a non-trivial version bump.

**Comment by joshmoore** [comment]
i.e. `5.6.0`?

**Comment by mtbc** [comment]
Sounds plausible. :smiley: How to proceed? I could add the `version = "5.6.0"` commit to this PR (and signed-tag it in this branch, or does that not "merge" from my fork?).

**Comment by joshmoore** [comment]
Bumping the commit here or on master is fine. The tag should be on master which wouldn't "merge" from your branch. (It _could_ be the merge commit itself, though)

**Comment by mtbc** [comment]
So once this is in I'll push a signed tag to `master` and open a PR to set the version to 5.6.1-SNAPSHOT.

**Comment by joshmoore** [comment]
:+1: for merging and tagging. You might also try pushing the SNAPSHOT bump directly to master.

**Comment by mtbc** [comment]
Is there a way I can now get this into https://artifacts.openmicroscopy.org/artifactory/maven/org/openmicroscopy/omero-model/5.6.0/ for https://github.com/ome/omero-blitz/pull/85?

**Comment by joshmoore** [comment]
Use the artifactory "move" functionality on the subfolder of the `ome.staging` repository to put it in the `ome.release` repository.

**Comment by jburel** [comment]
An entry for 5.6.0 was not added to the changelog. 
I have added one since I am pushing a 5.6.1

**Pull request merged**
