### PR TITLE
Try fixing the build issues from 2022-05-20

### PR DESCRIPTION
**Pull request by chris-allan**
.

### CODE REVIEW

**Comment by chris-allan** [comment]
For the existing artifacts.openmicroscopy.org and artifacts.glencoesoftware.com Artifactory deployments, legacy artifactoryonline.com repository caches may need to move to jfrog.io:

* https://jfrog.com/knowledge-base/deprecation-of-artifactoryonline-com-domain/

/cc @sbesson

**Comment by chris-allan** [comment]
`http://gradle.artifactoryonline.com/gradle/libs` --> `https://gradle.jfrog.io/artifactory/libs/` (`gradle-libs` repository cache)
`http://gradle.artifactoryonline.com/gradle/plugins` --> `https://gradle.jfrog.io/artifactory/plugin-portal-backend/` (`gradle-plugins` repository cache)

**Comment by chris-allan** [comment]
Switched `gradle-plugins` to `https://plugins.gradle.org/m2/` (as documented here: https://plugins.gradle.org/docs/mirroring) and removed `gradle-libs` from `artifacts.glencoesoftware.com`.

**Comment by sbesson** [comment]
Closing as the issue should have been mitigated upstream.

**Pull request closed without merging**
