### PR TITLE
Bump Bio-Formats to version 7.1.0

### PR DESCRIPTION
**Pull request by sbesson**
See https://www.openmicroscopy.org/2023/12/11/bio-formats-7-1-0.html

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-build-push#403](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/403/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/403/consoleText) for more details.
Possible conflicts:
  - PR #90 jburel 'bump org.openmicroscopy.project 5.6.0'
    - build.gradle
  - PR #96 dgault 'Bump BF version to 7.0.1'
    - build.gradle

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-build-push#404](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/404/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/404/consoleText) for more details.
Possible conflicts:
  - PR #90 jburel 'bump org.openmicroscopy.project 5.6.0'
    - build.gradle
  - PR #96 dgault 'Bump BF version to 7.0.1'
    - build.gradle

--conflicts

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Review by jburel — APPROVED** [review]

**Comment by jburel** [comment]
PR is included and all builds are green.

**Comment by sbesson** [comment]
>  @sbesson did you mean to push this branch to main repo and not open it from your account?
Not really, that was rather an oversight

**Pull request merged**
