### PR TITLE
Bump Bio-Formats version to 6.3.0

### PR DESCRIPTION
**Pull request by dgault**
Bumping Bio-Formats version to latest 6.2.1

### CODE REVIEW

**Comment by sbesson** [comment]
Note the primary impact to be discussed is that existing memo files would be invalidated if a server gets upgraded with this version of the Bio-Formats library.

**Comment by dgault** [comment]
New commit to bump to latest 6.3.0

**Comment by dgault** [comment]
New commit to bump to 6.3.1

**Comment by joshmoore** [comment]
Merging to start chaining this up the stack. Two remaining points will need to be considered:

 - release notes will need to mention the bfcache invalidation as usual
 - some testing on the (heavily) modified formats might be prudent

cc: @pwalczysko @jburel

**Comment by pwalczysko** [comment]
@dgault Is there any list of the abovementioned formats to test please ?

**Pull request merged**
